networks:
  server-network:
    ipam:
      config:
        - subnet: 172.128.0.0/24

services:
  ##### SSH SERVER ############################################################
  ssh-server:
    build: 
      context: ./ssh-server/docker
      dockerfile: Dockerfile
    container_name: ssh-server
    restart: always
    ports:
      - "2222:22"  # Le port local 2222 redirige vers le port 22 du conteneur
    networks:
      server-network:
        ipv4_address: 172.128.0.2
    cap_add:
      - NET_ADMIN  # Permet la gestion des tunnels réseau

  ##### DATABASE ##############################################################
  db:
    build:
      context: ./database
      dockerfile: docker/Dockerfile
    container_name: bourbabax-db
    restart: always
    ports:
      - "3306:3306"
    networks:
      server-network:
        ipv4_address: 172.128.0.3
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql

  ##### PHPMYADMIN ############################################################
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: bourbabax-phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - "8081:80"
    networks:
      server-network:
        ipv4_address: 172.128.0.4
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  ##### PRIVATE AIRNET ########################################################
  debian:
    build:
      context: ./private-airnet
      dockerfile: docker/Dockerfile
    container_name: bourbabax-private-airnet
    restart: always
    depends_on:
      - db
    ports:
      - "7880:7880"
    networks:
      server-network:
        ipv4_address: 172.128.0.5

  ##### API ###################################################################
  api:
    build:
      context: ./Server/api
      dockerfile: Dockerfile
    container_name: bourbabax-api
    restart: always
    depends_on:
      - db
    ports:
      - "3000:8000"
    networks:
      server-network:
        ipv4_address: 172.128.0.6
  #   volumes:
  #     - ./api:/app
  #   labels:
  #     - "traefik.http.routers.web.rule=Host(`airnet-api.bourbabax.com`)
  "

  ##### TRAEFIK ###############################################################
  traefik:
    image: traefik:v3.2 # Remplacer par la version de Traefik souhaitée
    command:
      - "--api.insecure=true" # Activer l'API de Traefik (non sécurisé)
      - "--providers.docker=true" # Activer le provider Docker pour Traefik
      - "--entrypoints.web.address=:80" # Écouter sur le port 80
    ports:
      - "80:80" # Trafic HTTP
      - "8080:8080" # Traefik dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock" # Permet à Traefik de communiquer avec Docker

volumes:
  mysql_data:
