FROM debian:latest

EXPOSE 22 80 8022 8080 8327 8443 18327
RUN apt-get -y update; apt-get -y install lsof curl autossh systemctl openssh-client gpg lsb-release
RUN apt-get install -y nginx
RUN apt-get install -y mosquitto mosquitto-clients

#COPY ../redis_install.sh /bin
#COPY ../register.sh /bin
#CMD ["bash", "/bin/register.sh"]

FROM redis:latest
COPY redis.conf /usr/local/etc/redis/redis.conf
CMD [ "redis-server", "/usr/local/etc/redis/redis.conf" ]