services:
  web:
    container_name: bourbabax-web-server
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
      - "2222:22" # SSH port forwarded to 2222 on host
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/index.html:/var/www/html/index.html
      - ./logs/nginx:/var/log/nginx
      - ./reverse_ssh_key.pub:/root/.ssh/authorized_keys
      - ./reverse_ssh_key:/root/.ssh/reverse_ssh_key
    networks:
      - server-network
  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: bourbabax-db
    volumes:
      - ./database/data:/var/lib/mysql
      - ./database:/app
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    networks:
      - server-network
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: bourbabax-phpmyadmin
    depends_on:
      - db

    ports:
      - "8081:80"

    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    networks:
      - server-network

  debian:
    build:
      context: ./private-airnet
      dockerfile: Dockerfile
    container_name: bourbabax-private-airnet
    depends_on:
      - db
    ports:
      - "7880:7880"
    networks:
      - server-network

networks:
  server-network:
    driver: bridge
