services:
  web:
    container_name: bourbabax-web-server
    image: nginx:latest
    ports:
      - "8080:80"
  db:
    container_name: bourbabax-db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: clients

