services:
  web:
    container_name: bourbabax-web-server
    image: nginx:latest
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - server-network
  db:
    container_name: bourbabax-db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: bourbabax256
      MYSQL_DATABASE: serverdb
      MYSQL_USER: www
      MYSQL_PASSWORD: bourbabax255
    volumes:
      - ./database/script-db.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/data:/var/lib/mysql
      - ./database:/app
    ports:
      - "3306:3306"
    networks:
      - server-network

networks:
  server-network:
    driver: bridge
