services:
  web:
    container_name: bourbabax-web-server
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  db:
    container_name: bourbabax-db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: bourbabax256
      MYSQL_DATABASE: clients
      MYSQL_USER: www
      MYSQL_PASSWORD: bourbabax255
    ports:
      - "3306:3306"
    volumes:
      - ./database/data:/var/lib/mysql
