networks:
  server-network:
    ipam:
      config:
        - subnet: 172.128.0.0/24

services:
  web:
    container_name: bourbabax-web-server

    build:
      context: ./nginx
      dockerfile: Dockerfile

    depends_on:
      - db

    ports:
      - "443:443" # HTTPS
      - "2222:22" # SSH port forwarded to 2222 on host

    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/index.html:/var/www/html/index.html
      - ./logs/nginx:/var/log/nginx
      # - ./reverse_ssh_key.pub:/root/.ssh/authorized_keys
      # - ./reverse_ssh_key:/root/.ssh/reverse_ssh_key

    networks:
      server-network:
        ipv4_address: 172.128.0.2

  db:
    build:
      context: ./database
      dockerfile: Dockerfile

    container_name: bourbabax-db

    volumes:
      - ./database/data:/var/lib/mysql
      - ./database:/app

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    ports:
      - "3308:3306"

    networks:
      server-network:
        ipv4_address: 172.128.0.3

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: bourbabax-phpmyadmin
    depends_on:
      - db
    ports:
      - "8081:80"

    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    networks:
      server-network:
        ipv4_address: 172.128.0.4

  debian:
    build:
      context: ./private-airnet
      dockerfile: Dockerfile
    container_name: bourbabax-private-airnet
    depends_on:
      - db
    ports:
      - "7880:7880"
    networks:
      server-network:
        ipv4_address: 172.128.0.5

  # api:
  #   container_name: bourbabax-api
  #   restart: always
  #   build:
  #     context: ./api
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - db
  #   ports:
  #     - "3000:8000"
  #   volumes:
  #     - ./api:/app

  reverse-proxy:
    image: traefik:v3.2
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8090:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  whoami:
    # A container that exposes an API to show its IP address
    image: traefik/whoami
    labels:
      - "traefik.http.routers.whoami.rule=Host(`whoami.docker.localhost`)"